const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
if(process.argv.includes('--link-check')){
 const modules=new Map();const context=vm.createContext({});function load(file){if(modules.has(file))return modules.get(file);let text=fs.readFileSync(file,'utf8');if(file===path.join(root,'js/config.js'))text=text.replace(/^export const LOGIN_REGION_ENABLED.*\r?\n/m,'');const m=new vm.SourceTextModule(text,{identifier:file,context});modules.set(file,m);return m;}
 (async()=>{for(const file of ['js/main.js','club/app.js']){const module=load(path.join(root,file));await module.link((name,ref)=>load(path.resolve(path.dirname(ref.identifier),name)));}console.log('COMPATIBLE');})().catch(e=>{console.error(e.message);process.exitCode=1;});
}else{
 const {test}=require('node:test'),{spawnSync}=require('node:child_process');
 test('los módulos completos del sistema y Club enlazan con config anterior sin la bandera nueva',()=>{const r=spawnSync(process.execPath,['--experimental-vm-modules',__filename,'--link-check'],{encoding:'utf8'});assert.equal(r.status,0,r.stderr);assert.match(r.stdout,/COMPATIBLE/);});
 function worker(file){const listeners={},events=[];let failed=false;const currentCache={match:async()=>({version:'current'}),put:async()=>{},addAll:async()=>{}};const ctx=vm.createContext({URL,Set,Promise,fetch:async()=>{if(failed)throw new Error('offline');return{ok:true,clone:()=>({}),version:'network'};},caches:{open:async()=>currentCache,match:async()=>({version:'foreign-old'}),keys:async()=>[],delete:async()=>true},self:{location:{origin:'https://system.test'},addEventListener:(name,fn)=>listeners[name]=fn,skipWaiting(){},clients:{claim:async()=>events.push('claim')}}});vm.runInContext(fs.readFileSync(path.join(root,file),'utf8'),ctx);return{listeners,events,offline:()=>failed=true,request:async(path,mode='cors')=>{let response;listeners.fetch({request:{method:'GET',url:'https://system.test'+path,mode,destination:'script'},respondWith:p=>response=p,waitUntil(){}});return response;}};}
 for(const [file,script,page] of [['sw.js','/js/config.js','/mobile.html'],['club/sw.js','/js/config.js','/club/index.html']]){
  test(file+': una caché de otra aplicación no sustituye la configuración de esta versión',async()=>{const w=worker(file);assert.equal((await w.request(script)).version,'current');});
  test(file+': sin red, la navegación usa únicamente su propia copia',async()=>{const w=worker(file);w.offline();assert.equal((await w.request(page,'navigate')).version,'current');});
 }
 test('la activación del sistema espera la limpieza antes de tomar las ventanas',async()=>{const w=worker('sw.js');let work;w.listeners.activate({waitUntil:p=>work=p});assert.equal(w.events.length,0);await work;assert.deepEqual(w.events,['claim']);});
 for(const file of ['mobile.html','desktop.html'])test(file+': al actualizar se recupera un módulo roto sin recargar una aplicación inicializada',()=>{const html=fs.readFileSync(path.join(root,file),'utf8');const source=html.match(/navigator\.serviceWorker\.addEventListener\('controllerchange',[\s\S]*?\n\s*\}\);/)[0];let handler,reloads=0;const ctx=vm.createContext({navigator:{serviceWorker:{addEventListener:(event,fn)=>handler=fn}},window:{location:{reload:()=>reloads++}}});vm.runInContext(source,ctx);handler();assert.equal(reloads,1);ctx.window.loginSubmit=()=>{};handler();assert.equal(reloads,1);assert.match(html,/register\('\/sw.js', \{ updateViaCache: 'none' \}\)/);});
}
